// Generated by the Course Repository local dev panel.
// Paste-over this whole file whenever the courses/ folder changes.
// Enrollment codes do NOT live here — they're in ENROLLMENT_CODES inside index.html.
window.COURSE_STRUCTURE = {
  "courses": [
    {
      "name": "Advance Algorithm Analysis",
      "weeks": [
        {
          "name": "Week 1",
          "files": [
            "Lec1.pdf",
            "Lec2.pdf",
            "Lec3.pdf"
          ]
        }
      ],
      "files": []
    },
    {
      "name": "Advance Operating Systems",
      "weeks": [
        {
          "name": "Book",
          "files": [
            "OS Internals and Design Principles (1).pdf"
          ]
        },
        {
          "name": "Week 1",
          "files": [
            "DOC-20260909-WA0038.pdf"
          ]
        }
      ],
      "files": [
        "CS-837_Advanced_OS course outline (1).pdf"
      ]
    },
    {
      "name": "Advance Theory of Computation",
      "weeks": [
        {
          "name": "Book",
          "files": []
        },
        {
          "name": "Week 1",
          "files": [
            "LLM_Basics_and_Course_Map.pptx",
            "Week1_Lecture_Notes.docx",
            "Week1_Slides.pptx"
          ]
        }
      ],
      "files": []
    },
    {
      "name": "Mathematical Methods for Computing",
      "weeks": [
        {
          "name": "Book",
          "files": [
            "Book-Mathematics for Machine Learning.pdf",
            "Bool-LA and its App by David clay.pdf"
          ]
        },
        {
          "name": "Week 1",
          "files": [
            "Introduction.pdf",
            "Practice Problems 1.pdf",
            "Vector algebra.pdf"
          ]
        },
        {
          "name": "Week 2",
          "files": [
            "Lecture week 2.pdf"
          ]
        }
      ],
      "files": [
        "CS-813_Mathematical Methods for Computing-A- Fall 2026.docx"
      ]
    },
    {
      "name": "Time Table",
      "weeks": [],
      "files": [
        "MSCS 2K26 Updated Timetable.png"
      ]
    },
    {
      "name": "Understanding of Quran 1",
      "weeks": [],
      "files": []
    }
  ]
};
